import Head from 'next/head'
import styles from '../styles/Home.module.css'

import Navbar from '../components/Navbar'
import HomePage from './home'
import ProjectsPage from './projects'
import TechnologiesPage from './technologies'
import ContactPage from './contact'
import Footer from '../components/Footer'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Bonaventura Bagas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/profile.ico" />
      </Head>

      <Navbar />
      <HomePage />
      <ProjectsPage />
      <TechnologiesPage />
      <ContactPage />
      <Footer />
    </div>
  )
}
